export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

<<<<<<< HEAD
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
=======
export default function RootLayout({
  children }) {

  return (
    <html lang="en">
      <body>
        {children}
      </body>
>>>>>>> 3ada4b85975cf81fbed532de54d5c424f140de66
    </html>
  );
}
