import Head from "next/head";
import Image from "next/image";
import styles from "./index.module.css";
import SideBar from "@/app/Components/Dashboard/SideBar";
import Header from "@/app/Components/Dashboard/Header";
import { Link } from "react-router-dom";
import NavBar from "@/app/Components/NavBar/NavBar";
import { useRouter } from "next/router";

export default function Dashboard() {
  const router = useRouter();
  const { section } = router.query;

  return (
    <div>
      {/* <NavBar /> */}

      <div></div>
      <div className={styles.container}>
        <SideBar></SideBar> <section className={styles.section}></section>
      </div>
    </div>
  );
}
//  <Head>
//       <title>Dashboard</title>

//       <meta
//         name="description"
//         content="Generated by create next app"
//       ></meta>
//       <meta
//         name="viewport"
//         content="width=device-width, initial-scale=1"
//       ></meta>

//       <link rel="icon" href="/favivon.ico"></link>
//     </Head>
