import Head from "next/head";
import Image from "next/image";
import styles from "./index.module.css";
import SideBar from "@/app/Components/Dashboard/SideBar";
import Header from "@/app/Components/Dashboard/Header";
import { Link } from "react-router-dom";

export default function Dashboard() {
  return (
    <div>
      {" "}
      <div className={styles.left}>
        <SideBar>
          <Head>
            <title>Dashboard</title>

            <meta
              name="description"
              content="Generated by create next app"
            ></meta>
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            ></meta>

            <link rel="icon" href="/favivon.ico"></link>
          </Head>
        </SideBar>{" "}
      </div>
      <div className={styles.right}>
        <main className={styles.main}>
          <Header />{" "}
        </main>
      </div>
    </div>
  );
}
